/* Generated by scripts/pwa.mjs - do not edit. */
const CACHE = 'deshrimp-r0vo8';
const SHELL = [
    "./index.html",
    "./assets/ibm-plex-sans-latin-IvpUvPa2.woff2",
    "./assets/ibm-plex-sans-latin-ext-CIII54If.woff2",
    "./assets/ibm-plex-sans-cyrillic-BAAhND-U.woff2",
    "./assets/ibm-plex-sans-cyrillic-ext-d45eAU9y.woff2",
    "./assets/ibm-plex-mono-500-latin-DSY6xOcd.woff2",
    "./assets/ibm-plex-mono-400-latin-DMJ8VG8y.woff2",
    "./assets/ibm-plex-mono-600-latin-BgSNZQsw.woff2",
    "./assets/index-CDQDhT9B.css",
    "./assets/index-B-a_Tcqy.js",
    "./assets/index-x0O6AKb-.js",
    "./assets/index-Ck4XQ4Dw.js",
    "./assets/index-CVhdH_gx.js",
    "./assets/index-BHdPEaF1.js",
    "./assets/index-B86YWiiT.js",
    "./assets/connection-handler-simple-peer-netvXV5t.js",
    "./icon.svg",
    "./icon-maskable.svg",
    "./manifest.webmanifest",
    "./brand/logo.svg",
    "./brand/mark.svg",
    "./snd/ahem.mp3",
    "./snd/fart.mp3",
    "./snd/knuckles.mp3",
    "./snd/rimshot.mp3",
    "./snd/scream.mp3",
    "./snd/whip.wav"
];

self.addEventListener('install', (event) => {
    // Individually, so one missing file cannot fail the whole install.
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        await Promise.all(SHELL.map((f) => cache.add(f).catch(() => {})));
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const names = await caches.keys();
        await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // A navigation always gets the shell: this is one page, and offline it is
    // still that page.
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            try {
                return await fetch(request);
            } catch {
                return (await caches.match('./index.html')) || Response.error();
            }
        })());
        return;
    }

    // Everything else: serve from cache when it is there, otherwise fetch and
    // keep a copy. This is what pulls the pose model in on first use.
    event.respondWith((async () => {
        const hit = await caches.match(request);
        if (hit) return hit;
        try {
            const response = await fetch(request);
            if (response.ok && response.type === 'basic') {
                const cache = await caches.open(CACHE);
                void cache.put(request, response.clone());
            }
            return response;
        } catch {
            return Response.error();
        }
    })());
});
