/* Generated by scripts/pwa.mjs - do not edit. */
const SHELL_CACHE = 'deshrimp-shell-z63x1o7';
const MODEL_CACHE = 'deshrimp-model-b1b5e665258c2108';
const SHELL = [
    "./index.html",
    "./de.html",
    "./en.html",
    "./es.html",
    "./fr.html",
    "./it.html",
    "./pt.html",
    "./nl.html",
    "./pl.html",
    "./tr.html",
    "./ru.html",
    "./zh.html",
    "./ja.html",
    "./ka.html",
    "./assets/ibm-plex-sans-latin-ext-CIII54If.woff2",
    "./assets/ibm-plex-sans-latin-IvpUvPa2.woff2",
    "./assets/ibm-plex-sans-cyrillic-BAAhND-U.woff2",
    "./assets/ibm-plex-sans-cyrillic-ext-d45eAU9y.woff2",
    "./assets/ibm-plex-mono-400-latin-DMJ8VG8y.woff2",
    "./assets/ibm-plex-mono-500-latin-DSY6xOcd.woff2",
    "./assets/ibm-plex-mono-600-latin-BgSNZQsw.woff2",
    "./assets/index-CDQDhT9B.css",
    "./assets/index-BA7o5KxP.js",
    "./assets/index-8TEiz2nX.js",
    "./assets/index-N7zNlC0q.js",
    "./assets/index-CFasBczC.js",
    "./assets/index-DMtVlAb4.js",
    "./assets/index-DPYiTaMm.js",
    "./assets/connection-handler-simple-peer-CwBVLtGI.js",
    "./icon.svg",
    "./icon-maskable.svg",
    "./manifest.webmanifest",
    "./brand/logo.svg",
    "./brand/mark.svg",
    "./snd/ahem.mp3",
    "./snd/fart.mp3",
    "./snd/knuckles.mp3",
    "./snd/rimshot.mp3",
    "./snd/scream.mp3",
    "./snd/whip.wav"
];

/* Everything the pose model needs, and the only thing kept across a deploy.
   Resolved against this worker's own URL rather than the origin root, because
   the site is also served from a subdirectory: GitHub Pages puts pull request
   previews under /pr-preview/<pr>/commit-<sha>/. */
const MODEL_DIR = new URL('mp/', self.location.href).href;

const isModel = (url) => url.href.startsWith(MODEL_DIR);

self.addEventListener('install', (event) => {
    // Individually, so one missing file cannot fail the whole install.
    event.waitUntil((async () => {
        const cache = await caches.open(SHELL_CACHE);
        await Promise.all(SHELL.map((f) => cache.add(f).catch(() => {})));
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        // The model cache survives here as long as the pin behind its name
        // does. That is the difference between a deploy and a re-download.
        const keep = new Set([SHELL_CACHE, MODEL_CACHE]);
        const names = await caches.keys();
        await Promise.all(names.filter((n) => !keep.has(n)).map((n) => caches.delete(n)));
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // A navigation gets its own page back when we have it - /de.html is a
    // different page from / in one respect that matters offline, which is the
    // language it opens in - and the root shell otherwise.
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            try {
                return await fetch(request);
            } catch {
                const cache = await caches.open(SHELL_CACHE);
                return (await cache.match(request, { ignoreSearch: true }))
                    || (await cache.match('./index.html'))
                    || Response.error();
            }
        })());
        return;
    }

    // Everything else: serve from cache when it is there, otherwise fetch and
    // keep a copy. This is what pulls the pose model in on first use.
    event.respondWith((async () => {
        const model = isModel(url);
        const cache = await caches.open(model ? MODEL_CACHE : SHELL_CACHE);
        const hit = await cache.match(request);
        if (hit) return hit;
        try {
            /* The model files have no hash in their names, so on a miss the
               HTTP cache could hand back bytes from before the pin moved, and
               they would then be stored under a name that promises otherwise.
               'no-cache' revalidates instead of re-downloading: a matching
               ETag is a 304 and the body still comes from the HTTP cache. */
            const response = await fetch(
                model ? new Request(request, { cache: 'no-cache' }) : request,
            );
            if (response.ok && response.type === 'basic') {
                void cache.put(request, response.clone());
            }
            return response;
        } catch {
            return Response.error();
        }
    })());
});
