/* Generated by scripts/pwa.mjs — do not edit. */
const CACHE = 'deshrimp-nz5ujq';
const SHELL = [
    "./index.html",
    "./assets/index-Ce7UMvc4.css",
    "./assets/index-B5Lv4o-T.js",
    "./assets/index-FrQKnV-l.js",
    "./assets/index-DeQKeSEZ.js",
    "./assets/index-DhFSe-4Z.js",
    "./assets/index-BnEZaz0V.js",
    "./assets/index-D3jBUnyu.js",
    "./assets/connection-handler-simple-peer-CrG6Zloz.js",
    "./icon.svg",
    "./manifest.webmanifest",
    "./snd/furz.mp3",
    "./snd/knacken.mp3",
    "./snd/raeuspern.mp3",
    "./snd/rimshot.mp3",
    "./snd/schrei.mp3"
];

self.addEventListener('install', (event) => {
    // Individually, so one missing file cannot fail the whole install.
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        await Promise.all(SHELL.map((f) => cache.add(f).catch(() => {})));
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const names = await caches.keys();
        await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // A navigation always gets the shell: this is one page, and offline it is
    // still that page.
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            try {
                return await fetch(request);
            } catch {
                return (await caches.match('./index.html')) || Response.error();
            }
        })());
        return;
    }

    // Everything else: serve from cache when it is there, otherwise fetch and
    // keep a copy. This is what pulls the pose model in on first use.
    event.respondWith((async () => {
        const hit = await caches.match(request);
        if (hit) return hit;
        try {
            const response = await fetch(request);
            if (response.ok && response.type === 'basic') {
                const cache = await caches.open(CACHE);
                void cache.put(request, response.clone());
            }
            return response;
        } catch {
            return Response.error();
        }
    })());
});
