/**
 * # lang-text — the frame's fixed words, in every language it speaks
 *
 * ## What it does and how it looks
 * Nothing on its own. One flat object per language, all with the same keys,
 * read by `uiText()` in `lang.ts`. Split out of that file on 2026-09-08, when
 * ten more languages turned a 300-line module into a 1,300-line one and its
 * actual logic — detection, the current value, the locale — became impossible
 * to find between the tables.
 *
 * ## Core parts
 * - `TEXT` — `Record<UiLang, UiText>`, and the type is what keeps it honest: a
 *   key added to `UiText` and forgotten in Japanese is a compile error, not a
 *   German word on a Japanese page.
 *
 * ## Examples
 * ```ts
 * import { TEXT } from './lang-text';
 * TEXT.ja.share;   // 共有
 * ```
 *
 * ## Changelog
 * - 2026-09-08 First version: `de`/`en` moved here unchanged, plus `es`, `fr`,
 *   `it`, `pt`, `nl`, `pl`, `tr`, `ru`, `zh`, `ja`.
 */

import type { UiLang, UiText } from './lang';

export const TEXT: Record<UiLang, UiText> = {
    de: {
        metaTitle: 'Zu dieser Seite',
        metaSubtitle: 'Die Anfrage, auf der sie beruht, und woher die Angaben stammen.',
        taskLabel: 'Aufgabe',
        gapsTitle: 'Datengrundlage',
        gapsSubtitle: 'Herkunft und Belastbarkeit der Angaben, auf denen diese Seite beruht.',
        gapsAskTitle: 'Beantworte das, dann wird die nächste Fassung besser',
        gapsAskText: 'Schreib mir die Antworten einfach in den Chat — ich trage sie ins Repo ein und baue die Seite neu.',
        gapsCopied: 'Fragen kopiert',
        gapsCopyFailed: 'Kopieren hat nicht geklappt',
        severityMissing: 'fehlt',
        severityAssumed: 'angenommen',
        severityStale: 'veraltet',
        severityMissingHint: 'Dazu steht nichts im Repo.',
        severityAssumedHint: 'Ich habe eine Annahme eingesetzt.',
        severityStaleHint: 'Gespeichert, aber möglicherweise nicht mehr aktuell.',
        sourcesTitle: 'Quellen',
        share: 'Teilen',
        themeLight: 'Helles Design',
        themeDark: 'Dunkles Design',
        confirmTitle: 'Sicher?',
        confirmYes: 'Ja, machen',
        confirmNo: 'Abbrechen',
        close: 'Schließen',
        shareTitle: 'Seite teilen',
        copyLink: 'Link kopieren',
        linkCopied: 'Link kopiert',
        copyFailed: 'Kopieren hat nicht geklappt',
        shareLocalFile: 'Diese Seite läuft als lokale Datei. Der Link unten zeigt auf deine Festplatte — erst die veröffentlichte Fassung lässt sich teilen.',
        shareTooLongForQr: 'Die Adresse ist zu lang für einen QR-Code. Der Link funktioniert trotzdem.',
        shareLinkIsTheLock: 'Der Link ist das Schloss: wer ihn hat, kann die Seite lesen.',
        shareNative: 'Teilen…',
        shareFailed: 'Teilen fehlgeschlagen',
        copyUnsupported: 'Kopieren geht in diesem Browser nicht',
        scanWithPhone: 'Mit der Handykamera scannen',
        checkedToday: () => 'heute geprüft',
        checkedDaysAgo: (days: number) => `vor ${days} Tagen`,
        assumedInstead: 'Stattdessen benutzt: ',
        wobbles: 'Wackelt dadurch: ',
        asOf: 'Stand',
        why: 'Warum',
        criterion: 'Kriterium',
        must: 'Muss',
        out: 'raus',
        mustFailed: 'Ein Muss-Kriterium ist nicht erfüllt.',
        more: 'Mehr',
        nothingFound: 'Nichts gefunden',
        noEntries: 'Keine Einträge',
        noCoordinates: 'Keine Koordinaten',
        mapSketch: 'Kartenskizze',
        pickOnMap: 'Ziel auf der Karte wählen',
        latitude: 'Breite',
        longitude: 'Länge',
        openInMaps: 'In Maps öffnen',
        qrTooLong: 'Zu lang für einen QR-Code.',
        qrFor: (value: string) => 'QR-Code für ' + value,
        ingredients: 'Zutaten',
        method: 'So geht’s',
        recipeImageMissing: 'Bild fehlt — jedes Rezept braucht eins',
        toShop: 'Zum Shop',
        owned: 'hab ich',
        topPick: 'Top-Pick',
        perNight: 'pro Nacht',
        nights: (n: number) => n + (n === 1 ? ' Nacht' : ' Nächte'),
        playerLoading: 'Player lädt …',
        checkedAgainstOriginal: 'Am Original nachgesehen.',
        notChecked: 'Nicht nachgesehen — kann falsch sein.',
        copyQuestions: 'Fragen kopieren',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Daten sichern und übertragen',
        syncIntro: 'Alles, was diese Seite sich merkt, liegt in diesem Browser. Hier holst du es heraus, bringst es zurück oder hältst ein zweites Gerät auf demselben Stand.',
        syncFileTitle: 'Datei',
        syncFileNote: 'Eine JSON-Datei auf deiner Platte. Braucht kein Konto, keine Verbindung und funktioniert auch noch in zehn Jahren. Beim Laden wird zusammengeführt, nicht ersetzt.',
        syncExport: 'Als Datei speichern',
        syncImport: 'Aus Datei laden',
        syncImported: (rows: number) => `${rows} Einträge geladen`,
        syncCloudTitle: 'Cloud-Speicher',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Läuft in einen versteckten Ordner, der nur dieser Seite gehört — deine übrigen Dateien bleiben unsichtbar. Die Verbindung hält, solange die Seite offen ist; nach etwa einer Stunde läuft die Anmeldung ab und du verbindest neu.',
        syncConnect: 'Verbinden',
        syncDisconnect: 'Trennen',
        syncConnected: 'Verbunden',
        syncNeedsClientId: 'Dafür brauchst du eine eigene OAuth-Client-ID beim Anbieter — kostenlos, einmal angelegt. Trag sie hier ein; sie bleibt in diesem Browser und wird nirgends hingeschickt.',
        syncP2PTitle: 'P2P zum anderen Gerät',
        syncP2PNote: 'Die Geräte reden direkt miteinander, die Daten laufen über keinen Server. Der Code ist gleichzeitig das Passwort: wer ihn hat, syncht mit dir. Gib ihn nur weiter, wenn du das willst.',
        syncCode: 'Dein Code',
        syncClientIdLabel: 'OAuth-Client-ID',
        syncSaveAndConnect: 'Speichern und verbinden',
        syncJoinCode: 'Code von jemand anderem',
        syncJoinHint: 'Hier den Code einsetzen, den du bekommen hast. Steht hier etwas, wird der benutzt statt deines eigenen.',
        syncNewCode: 'Neuen Code',
        syncCopy: 'Kopieren',
        syncCopied: 'Kopiert',
        syncStart: 'Starten',
        syncStop: 'Stoppen',
        syncBothOpen: 'Beide Geräte müssen dabei gleichzeitig offen sein.',
        syncFailed: (reason: string) => `Hat nicht geklappt: ${reason}`,
    },
    en: {
        metaTitle: 'About this page',
        metaSubtitle: 'The request it answers, and where the numbers come from.',
        taskLabel: 'Request',
        gapsTitle: 'What this is based on',
        gapsSubtitle: 'Where the information comes from, and how far it can be trusted.',
        gapsAskTitle: 'Answer these and the next version gets better',
        gapsAskText: 'Just write the answers into the chat — they go into the repo and the page is rebuilt.',
        gapsCopied: 'Questions copied',
        gapsCopyFailed: 'Copying did not work',
        severityMissing: 'missing',
        severityAssumed: 'assumed',
        severityStale: 'out of date',
        severityMissingHint: 'There is nothing about this in the repo.',
        severityAssumedHint: 'An assumption was used here.',
        severityStaleHint: 'Stored, but possibly no longer current.',
        sourcesTitle: 'Sources',
        share: 'Share',
        themeLight: 'Light theme',
        themeDark: 'Dark theme',
        confirmTitle: 'Are you sure?',
        confirmYes: 'Yes, do it',
        confirmNo: 'Cancel',
        close: 'Close',
        shareTitle: 'Share this page',
        copyLink: 'Copy link',
        linkCopied: 'Link copied',
        copyFailed: 'Copying did not work',
        shareLocalFile: 'This page is running as a local file. The link below points at your own disk — only the published version can be shared.',
        shareTooLongForQr: 'The address is too long for a QR code. The link still works.',
        shareLinkIsTheLock: 'The link is the lock: whoever has it can read the page.',
        shareNative: 'Share…',
        shareFailed: 'Sharing failed',
        copyUnsupported: 'This browser cannot copy to the clipboard',
        scanWithPhone: 'Scan with your phone camera',
        checkedToday: () => 'checked today',
        checkedDaysAgo: (days: number) => `${days} days ago`,
        assumedInstead: 'Assumed instead: ',
        wobbles: 'What that shifts: ',
        asOf: 'As of',
        why: 'Why',
        criterion: 'Criterion',
        must: 'Must',
        out: 'out',
        mustFailed: 'A must-have criterion is not met.',
        more: 'More',
        nothingFound: 'Nothing found',
        noEntries: 'No entries',
        noCoordinates: 'No coordinates',
        mapSketch: 'Map sketch',
        pickOnMap: 'Pick a spot on the map',
        latitude: 'Latitude',
        longitude: 'Longitude',
        openInMaps: 'Open in Maps',
        qrTooLong: 'Too long for a QR code.',
        qrFor: (value: string) => 'QR code for ' + value,
        ingredients: 'Ingredients',
        method: 'Method',
        recipeImageMissing: 'Picture missing — every recipe needs one',
        toShop: 'To the shop',
        owned: 'own it',
        topPick: 'Top pick',
        perNight: 'per night',
        nights: (n: number) => n + (n === 1 ? ' night' : ' nights'),
        playerLoading: 'Player loading …',
        checkedAgainstOriginal: 'Checked against the original.',
        notChecked: 'Not checked — may be wrong.',
        copyQuestions: 'Copy questions',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Back up and move your data',
        syncIntro: 'Everything this page remembers lives in this browser. Here you can take it out, put it back, or keep a second device on the same footing.',
        syncFileTitle: 'File',
        syncFileNote: 'A JSON file on your own disk. No account, no connection, and it still opens in ten years. Loading one merges it in rather than replacing what is there.',
        syncExport: 'Save as a file',
        syncImport: 'Load from a file',
        syncImported: (rows: number) => `${rows} entries loaded`,
        syncCloudTitle: 'Cloud storage',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Syncs into a hidden folder that belongs to this page alone — the rest of your files stay out of view. It runs while the page is open; the sign-in expires after about an hour and you connect again.',
        syncConnect: 'Connect',
        syncDisconnect: 'Disconnect',
        syncConnected: 'Connected',
        syncNeedsClientId: 'You need your own OAuth client id from the provider — free, created once. Paste it here; it stays in this browser and is sent nowhere.',
        syncP2PTitle: 'P2P to another device',
        syncP2PNote: 'The devices talk to each other directly; nothing travels through a server. The code is also the password: whoever has it syncs with you. Only hand it to someone you mean to.',
        syncCode: 'Your code',
        syncClientIdLabel: 'OAuth client id',
        syncSaveAndConnect: 'Save and connect',
        syncJoinCode: 'Someone else’s code',
        syncJoinHint: 'Paste the code you were given. While there is something here, it is used instead of your own.',
        syncNewCode: 'New code',
        syncCopy: 'Copy',
        syncCopied: 'Copied',
        syncStart: 'Start',
        syncStop: 'Stop',
        syncBothOpen: 'Both devices have to be open at the same time.',
        syncFailed: (reason: string) => `That did not work: ${reason}`,
    },
    es: {
        metaTitle: 'Sobre esta página',
        metaSubtitle: 'La petición de la que parte y de dónde salen los datos.',
        taskLabel: 'Petición',
        gapsTitle: 'En qué se basa',
        gapsSubtitle: 'De dónde viene la información y hasta qué punto es fiable.',
        gapsAskTitle: 'Responde a esto y la próxima versión será mejor',
        gapsAskText: 'Escribe las respuestas en el chat — se guardan en el repositorio y la página se vuelve a generar.',
        gapsCopied: 'Preguntas copiadas',
        gapsCopyFailed: 'No se pudo copiar',
        severityMissing: 'falta',
        severityAssumed: 'supuesto',
        severityStale: 'desactualizado',
        severityMissingHint: 'No hay nada sobre esto en el repositorio.',
        severityAssumedHint: 'Aquí se ha usado una suposición.',
        severityStaleHint: 'Está guardado, pero puede que ya no sea actual.',
        sourcesTitle: 'Fuentes',
        share: 'Compartir',
        themeLight: 'Tema claro',
        themeDark: 'Tema oscuro',
        confirmTitle: '¿Seguro?',
        confirmYes: 'Sí, hazlo',
        confirmNo: 'Cancelar',
        close: 'Cerrar',
        shareTitle: 'Compartir esta página',
        copyLink: 'Copiar enlace',
        linkCopied: 'Enlace copiado',
        copyFailed: 'No se pudo copiar',
        shareLocalFile: 'Esta página se está ejecutando como archivo local. El enlace de abajo apunta a tu propio disco — solo se puede compartir la versión publicada.',
        shareTooLongForQr: 'La dirección es demasiado larga para un código QR. El enlace funciona igualmente.',
        shareLinkIsTheLock: 'El enlace es la cerradura: quien lo tenga puede leer la página.',
        shareNative: 'Compartir…',
        shareFailed: 'No se pudo compartir',
        copyUnsupported: 'Este navegador no puede copiar al portapapeles',
        scanWithPhone: 'Escanéalo con la cámara del móvil',
        checkedToday: () => 'comprobado hoy',
        checkedDaysAgo: (days: number) => `hace ${days} días`,
        assumedInstead: 'Se ha supuesto: ',
        wobbles: 'Lo que eso mueve: ',
        asOf: 'A fecha de',
        why: 'Por qué',
        criterion: 'Criterio',
        must: 'Imprescindible',
        out: 'fuera',
        mustFailed: 'No se cumple un criterio imprescindible.',
        more: 'Más',
        nothingFound: 'No se ha encontrado nada',
        noEntries: 'Sin entradas',
        noCoordinates: 'Sin coordenadas',
        mapSketch: 'Croquis del mapa',
        pickOnMap: 'Elige un punto en el mapa',
        latitude: 'Latitud',
        longitude: 'Longitud',
        openInMaps: 'Abrir en Maps',
        qrTooLong: 'Demasiado largo para un código QR.',
        qrFor: (value: string) => 'Código QR de ' + value,
        ingredients: 'Ingredientes',
        method: 'Preparación',
        recipeImageMissing: 'Falta la foto — toda receta necesita una',
        toShop: 'Ir a la tienda',
        owned: 'ya lo tengo',
        topPick: 'La mejor opción',
        perNight: 'por noche',
        nights: (n: number) => n + (n === 1 ? ' noche' : ' noches'),
        playerLoading: 'Cargando el reproductor …',
        checkedAgainstOriginal: 'Comprobado en el original.',
        notChecked: 'Sin comprobar — puede estar mal.',
        copyQuestions: 'Copiar preguntas',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Guardar y trasladar tus datos',
        syncIntro: 'Todo lo que esta página recuerda está en este navegador. Aquí lo sacas, lo devuelves o pones un segundo aparato al día.',
        syncFileTitle: 'Archivo',
        syncFileNote: 'Un archivo JSON en tu propio disco. Sin cuenta, sin conexión, y dentro de diez años se seguirá abriendo. Al cargarlo se fusiona, no se reemplaza.',
        syncExport: 'Guardar como archivo',
        syncImport: 'Cargar desde archivo',
        syncImported: (rows: number) => `${rows} entradas cargadas`,
        syncCloudTitle: 'Almacenamiento en la nube',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Sincroniza en una carpeta oculta que pertenece solo a esta página — tus demás archivos quedan fuera de la vista. Funciona mientras la página esté abierta; la sesión caduca en una hora aproximadamente y vuelves a conectar.',
        syncConnect: 'Conectar',
        syncDisconnect: 'Desconectar',
        syncConnected: 'Conectado',
        syncNeedsClientId: 'Necesitas tu propio ID de cliente OAuth del proveedor — gratis, se crea una vez. Pégalo aquí; se queda en este navegador y no se envía a ninguna parte.',
        syncP2PTitle: 'P2P a otro aparato',
        syncP2PNote: 'Los aparatos hablan entre sí directamente; nada pasa por un servidor. El código es también la contraseña: quien lo tenga sincroniza contigo. Dáselo solo a quien quieras.',
        syncCode: 'Tu código',
        syncClientIdLabel: 'ID de cliente OAuth',
        syncSaveAndConnect: 'Guardar y conectar',
        syncJoinCode: 'El código de otra persona',
        syncJoinHint: 'Pega aquí el código que te han pasado. Mientras haya algo, se usa ese en vez del tuyo.',
        syncNewCode: 'Código nuevo',
        syncCopy: 'Copiar',
        syncCopied: 'Copiado',
        syncStart: 'Empezar',
        syncStop: 'Parar',
        syncBothOpen: 'Los dos aparatos tienen que estar abiertos a la vez.',
        syncFailed: (reason: string) => `No ha funcionado: ${reason}`,
    },
    fr: {
        metaTitle: 'À propos de cette page',
        metaSubtitle: 'La demande à laquelle elle répond, et d’où viennent les chiffres.',
        taskLabel: 'Demande',
        gapsTitle: 'Sur quoi elle repose',
        gapsSubtitle: 'D’où viennent les informations et jusqu’où on peut s’y fier.',
        gapsAskTitle: 'Réponds à ça et la prochaine version sera meilleure',
        gapsAskText: 'Écris simplement les réponses dans le chat — elles vont dans le dépôt et la page est régénérée.',
        gapsCopied: 'Questions copiées',
        gapsCopyFailed: 'La copie n’a pas fonctionné',
        severityMissing: 'manquant',
        severityAssumed: 'supposé',
        severityStale: 'périmé',
        severityMissingHint: 'Il n’y a rien là-dessus dans le dépôt.',
        severityAssumedHint: 'Une hypothèse a été utilisée ici.',
        severityStaleHint: 'Enregistré, mais peut-être plus à jour.',
        sourcesTitle: 'Sources',
        share: 'Partager',
        themeLight: 'Thème clair',
        themeDark: 'Thème sombre',
        confirmTitle: 'Vraiment ?',
        confirmYes: 'Oui, vas-y',
        confirmNo: 'Annuler',
        close: 'Fermer',
        shareTitle: 'Partager cette page',
        copyLink: 'Copier le lien',
        linkCopied: 'Lien copié',
        copyFailed: 'La copie n’a pas fonctionné',
        shareLocalFile: 'Cette page tourne comme fichier local. Le lien ci-dessous pointe vers ton disque — seule la version publiée peut être partagée.',
        shareTooLongForQr: 'L’adresse est trop longue pour un QR code. Le lien fonctionne quand même.',
        shareLinkIsTheLock: 'Le lien est la serrure : qui l’a peut lire la page.',
        shareNative: 'Partager…',
        shareFailed: 'Le partage a échoué',
        copyUnsupported: 'Ce navigateur ne peut pas copier dans le presse-papiers',
        scanWithPhone: 'Scanner avec l’appareil photo du téléphone',
        checkedToday: () => 'vérifié aujourd’hui',
        checkedDaysAgo: (days: number) => `il y a ${days} jours`,
        assumedInstead: 'Hypothèse retenue : ',
        wobbles: 'Ce que ça déplace : ',
        asOf: 'Au',
        why: 'Pourquoi',
        criterion: 'Critère',
        must: 'Impératif',
        out: 'écarté',
        mustFailed: 'Un critère impératif n’est pas rempli.',
        more: 'Plus',
        nothingFound: 'Rien trouvé',
        noEntries: 'Aucune entrée',
        noCoordinates: 'Pas de coordonnées',
        mapSketch: 'Croquis de carte',
        pickOnMap: 'Choisir un point sur la carte',
        latitude: 'Latitude',
        longitude: 'Longitude',
        openInMaps: 'Ouvrir dans Maps',
        qrTooLong: 'Trop long pour un QR code.',
        qrFor: (value: string) => 'QR code pour ' + value,
        ingredients: 'Ingrédients',
        method: 'Préparation',
        recipeImageMissing: 'Photo manquante — chaque recette en a besoin',
        toShop: 'Vers la boutique',
        owned: 'je l’ai',
        topPick: 'Notre préféré',
        perNight: 'par nuit',
        nights: (n: number) => n + (n === 1 ? ' nuit' : ' nuits'),
        playerLoading: 'Chargement du lecteur …',
        checkedAgainstOriginal: 'Vérifié sur l’original.',
        notChecked: 'Pas vérifié — peut être faux.',
        copyQuestions: 'Copier les questions',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Sauvegarder et déplacer tes données',
        syncIntro: 'Tout ce que cette page retient vit dans ce navigateur. Ici tu peux le sortir, le remettre, ou mettre un deuxième appareil au même niveau.',
        syncFileTitle: 'Fichier',
        syncFileNote: 'Un fichier JSON sur ton propre disque. Pas de compte, pas de connexion, et il s’ouvrira encore dans dix ans. Le charger fusionne au lieu de remplacer.',
        syncExport: 'Enregistrer dans un fichier',
        syncImport: 'Charger depuis un fichier',
        syncImported: (rows: number) => `${rows} entrées chargées`,
        syncCloudTitle: 'Stockage en ligne',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Synchronise dans un dossier caché qui n’appartient qu’à cette page — le reste de tes fichiers reste hors de vue. Ça tourne tant que la page est ouverte ; la connexion expire au bout d’une heure environ et tu la relances.',
        syncConnect: 'Connecter',
        syncDisconnect: 'Déconnecter',
        syncConnected: 'Connecté',
        syncNeedsClientId: 'Il te faut ton propre identifiant client OAuth chez le fournisseur — gratuit, créé une fois. Colle-le ici ; il reste dans ce navigateur et n’est envoyé nulle part.',
        syncP2PTitle: 'P2P vers un autre appareil',
        syncP2PNote: 'Les appareils se parlent directement ; rien ne passe par un serveur. Le code est aussi le mot de passe : qui l’a se synchronise avec toi. Ne le donne qu’à qui tu veux.',
        syncCode: 'Ton code',
        syncClientIdLabel: 'Identifiant client OAuth',
        syncSaveAndConnect: 'Enregistrer et connecter',
        syncJoinCode: 'Le code de quelqu’un d’autre',
        syncJoinHint: 'Colle ici le code qu’on t’a donné. Tant qu’il y a quelque chose, c’est lui qui sert, pas le tien.',
        syncNewCode: 'Nouveau code',
        syncCopy: 'Copier',
        syncCopied: 'Copié',
        syncStart: 'Démarrer',
        syncStop: 'Arrêter',
        syncBothOpen: 'Les deux appareils doivent être ouverts en même temps.',
        syncFailed: (reason: string) => `Ça n’a pas marché : ${reason}`,
    },
    it: {
        metaTitle: 'Su questa pagina',
        metaSubtitle: 'La richiesta da cui nasce e da dove vengono i dati.',
        taskLabel: 'Richiesta',
        gapsTitle: 'Su cosa si basa',
        gapsSubtitle: 'Da dove vengono le informazioni e quanto ci si può fidare.',
        gapsAskTitle: 'Rispondi a queste e la prossima versione sarà migliore',
        gapsAskText: 'Scrivi le risposte in chat — finiscono nel repository e la pagina viene rigenerata.',
        gapsCopied: 'Domande copiate',
        gapsCopyFailed: 'La copia non ha funzionato',
        severityMissing: 'manca',
        severityAssumed: 'ipotizzato',
        severityStale: 'non aggiornato',
        severityMissingHint: 'Nel repository non c’è nulla al riguardo.',
        severityAssumedHint: 'Qui è stata usata un’ipotesi.',
        severityStaleHint: 'Salvato, ma forse non è più attuale.',
        sourcesTitle: 'Fonti',
        share: 'Condividi',
        themeLight: 'Tema chiaro',
        themeDark: 'Tema scuro',
        confirmTitle: 'Sicuro?',
        confirmYes: 'Sì, procedi',
        confirmNo: 'Annulla',
        close: 'Chiudi',
        shareTitle: 'Condividi questa pagina',
        copyLink: 'Copia il link',
        linkCopied: 'Link copiato',
        copyFailed: 'La copia non ha funzionato',
        shareLocalFile: 'Questa pagina gira come file locale. Il link qui sotto punta al tuo disco — si può condividere solo la versione pubblicata.',
        shareTooLongForQr: 'L’indirizzo è troppo lungo per un codice QR. Il link funziona lo stesso.',
        shareLinkIsTheLock: 'Il link è la serratura: chi ce l’ha può leggere la pagina.',
        shareNative: 'Condividi…',
        shareFailed: 'Condivisione non riuscita',
        copyUnsupported: 'Questo browser non può copiare negli appunti',
        scanWithPhone: 'Inquadra con la fotocamera del telefono',
        checkedToday: () => 'verificato oggi',
        checkedDaysAgo: (days: number) => `${days} giorni fa`,
        assumedInstead: 'Ipotesi usata: ',
        wobbles: 'Cosa cambia: ',
        asOf: 'Aggiornato al',
        why: 'Perché',
        criterion: 'Criterio',
        must: 'Obbligatorio',
        out: 'escluso',
        mustFailed: 'Un criterio obbligatorio non è soddisfatto.',
        more: 'Altro',
        nothingFound: 'Nessun risultato',
        noEntries: 'Nessuna voce',
        noCoordinates: 'Nessuna coordinata',
        mapSketch: 'Schizzo della mappa',
        pickOnMap: 'Scegli un punto sulla mappa',
        latitude: 'Latitudine',
        longitude: 'Longitudine',
        openInMaps: 'Apri in Maps',
        qrTooLong: 'Troppo lungo per un codice QR.',
        qrFor: (value: string) => 'Codice QR per ' + value,
        ingredients: 'Ingredienti',
        method: 'Preparazione',
        recipeImageMissing: 'Manca la foto — ogni ricetta ne ha bisogno',
        toShop: 'Vai al negozio',
        owned: 'ce l’ho',
        topPick: 'La scelta migliore',
        perNight: 'a notte',
        nights: (n: number) => n + (n === 1 ? ' notte' : ' notti'),
        playerLoading: 'Caricamento del player …',
        checkedAgainstOriginal: 'Verificato sull’originale.',
        notChecked: 'Non verificato — potrebbe essere sbagliato.',
        copyQuestions: 'Copia le domande',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Salvare e spostare i tuoi dati',
        syncIntro: 'Tutto quello che questa pagina ricorda sta in questo browser. Qui lo tiri fuori, lo rimetti dentro, o allinei un secondo dispositivo.',
        syncFileTitle: 'File',
        syncFileNote: 'Un file JSON sul tuo disco. Nessun account, nessuna connessione, e fra dieci anni si aprirà ancora. Caricarlo unisce, non sostituisce.',
        syncExport: 'Salva come file',
        syncImport: 'Carica da file',
        syncImported: (rows: number) => `${rows} voci caricate`,
        syncCloudTitle: 'Archiviazione nel cloud',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Sincronizza in una cartella nascosta che appartiene solo a questa pagina — il resto dei tuoi file resta fuori dalla vista. Funziona finché la pagina è aperta; l’accesso scade dopo circa un’ora e ti ricolleghi.',
        syncConnect: 'Collega',
        syncDisconnect: 'Scollega',
        syncConnected: 'Collegato',
        syncNeedsClientId: 'Ti serve un tuo client id OAuth dal provider — gratuito, si crea una volta. Incollalo qui; resta in questo browser e non viene mandato da nessuna parte.',
        syncP2PTitle: 'P2P a un altro dispositivo',
        syncP2PNote: 'I dispositivi si parlano direttamente; niente passa da un server. Il codice è anche la password: chi ce l’ha si sincronizza con te. Dallo solo a chi vuoi.',
        syncCode: 'Il tuo codice',
        syncClientIdLabel: 'Client id OAuth',
        syncSaveAndConnect: 'Salva e collega',
        syncJoinCode: 'Il codice di un’altra persona',
        syncJoinHint: 'Incolla qui il codice che ti hanno dato. Finché c’è qualcosa, si usa quello e non il tuo.',
        syncNewCode: 'Nuovo codice',
        syncCopy: 'Copia',
        syncCopied: 'Copiato',
        syncStart: 'Avvia',
        syncStop: 'Ferma',
        syncBothOpen: 'I due dispositivi devono essere aperti nello stesso momento.',
        syncFailed: (reason: string) => `Non ha funzionato: ${reason}`,
    },
    pt: {
        metaTitle: 'Sobre esta página',
        metaSubtitle: 'O pedido de que parte e de onde vêm os dados.',
        taskLabel: 'Pedido',
        gapsTitle: 'Em que se baseia',
        gapsSubtitle: 'De onde vem a informação e até que ponto é de confiança.',
        gapsAskTitle: 'Responde a isto e a próxima versão fica melhor',
        gapsAskText: 'Escreve as respostas no chat — vão para o repositório e a página é gerada de novo.',
        gapsCopied: 'Perguntas copiadas',
        gapsCopyFailed: 'Não foi possível copiar',
        severityMissing: 'falta',
        severityAssumed: 'assumido',
        severityStale: 'desatualizado',
        severityMissingHint: 'Não há nada sobre isto no repositório.',
        severityAssumedHint: 'Aqui foi usado um pressuposto.',
        severityStaleHint: 'Está guardado, mas pode já não estar atual.',
        sourcesTitle: 'Fontes',
        share: 'Partilhar',
        themeLight: 'Tema claro',
        themeDark: 'Tema escuro',
        confirmTitle: 'De certeza?',
        confirmYes: 'Sim, avança',
        confirmNo: 'Cancelar',
        close: 'Fechar',
        shareTitle: 'Partilhar esta página',
        copyLink: 'Copiar ligação',
        linkCopied: 'Ligação copiada',
        copyFailed: 'Não foi possível copiar',
        shareLocalFile: 'Esta página está a correr como ficheiro local. A ligação abaixo aponta para o teu disco — só a versão publicada pode ser partilhada.',
        shareTooLongForQr: 'O endereço é comprido demais para um código QR. A ligação funciona à mesma.',
        shareLinkIsTheLock: 'A ligação é a fechadura: quem a tiver pode ler a página.',
        shareNative: 'Partilhar…',
        shareFailed: 'A partilha falhou',
        copyUnsupported: 'Este navegador não consegue copiar para a área de transferência',
        scanWithPhone: 'Digitaliza com a câmara do telemóvel',
        checkedToday: () => 'verificado hoje',
        checkedDaysAgo: (days: number) => `há ${days} dias`,
        assumedInstead: 'Pressuposto usado: ',
        wobbles: 'O que isso desloca: ',
        asOf: 'Em',
        why: 'Porquê',
        criterion: 'Critério',
        must: 'Obrigatório',
        out: 'fora',
        mustFailed: 'Um critério obrigatório não está cumprido.',
        more: 'Mais',
        nothingFound: 'Nada encontrado',
        noEntries: 'Sem entradas',
        noCoordinates: 'Sem coordenadas',
        mapSketch: 'Esboço do mapa',
        pickOnMap: 'Escolhe um ponto no mapa',
        latitude: 'Latitude',
        longitude: 'Longitude',
        openInMaps: 'Abrir no Maps',
        qrTooLong: 'Comprido demais para um código QR.',
        qrFor: (value: string) => 'Código QR de ' + value,
        ingredients: 'Ingredientes',
        method: 'Preparação',
        recipeImageMissing: 'Falta a foto — toda a receita precisa de uma',
        toShop: 'Ir à loja',
        owned: 'já tenho',
        topPick: 'A melhor escolha',
        perNight: 'por noite',
        nights: (n: number) => n + (n === 1 ? ' noite' : ' noites'),
        playerLoading: 'A carregar o leitor …',
        checkedAgainstOriginal: 'Verificado no original.',
        notChecked: 'Não verificado — pode estar errado.',
        copyQuestions: 'Copiar perguntas',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Guardar e mover os teus dados',
        syncIntro: 'Tudo o que esta página guarda está neste navegador. Aqui tiras isso, voltas a pôr, ou pões um segundo aparelho ao mesmo nível.',
        syncFileTitle: 'Ficheiro',
        syncFileNote: 'Um ficheiro JSON no teu disco. Sem conta, sem ligação, e daqui a dez anos ainda abre. Carregá-lo junta em vez de substituir.',
        syncExport: 'Guardar como ficheiro',
        syncImport: 'Carregar de um ficheiro',
        syncImported: (rows: number) => `${rows} entradas carregadas`,
        syncCloudTitle: 'Armazenamento na nuvem',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Sincroniza para uma pasta escondida que pertence só a esta página — os teus outros ficheiros ficam fora de vista. Funciona enquanto a página estiver aberta; a sessão expira ao fim de cerca de uma hora e voltas a ligar.',
        syncConnect: 'Ligar',
        syncDisconnect: 'Desligar',
        syncConnected: 'Ligado',
        syncNeedsClientId: 'Precisas do teu próprio client id de OAuth do fornecedor — gratuito, criado uma vez. Cola-o aqui; fica neste navegador e não é enviado para lado nenhum.',
        syncP2PTitle: 'P2P para outro aparelho',
        syncP2PNote: 'Os aparelhos falam diretamente um com o outro; nada passa por um servidor. O código é também a palavra-passe: quem o tiver sincroniza contigo. Só o dês a quem quiseres.',
        syncCode: 'O teu código',
        syncClientIdLabel: 'Client id de OAuth',
        syncSaveAndConnect: 'Guardar e ligar',
        syncJoinCode: 'O código de outra pessoa',
        syncJoinHint: 'Cola aqui o código que te deram. Enquanto houver alguma coisa, usa-se esse em vez do teu.',
        syncNewCode: 'Código novo',
        syncCopy: 'Copiar',
        syncCopied: 'Copiado',
        syncStart: 'Começar',
        syncStop: 'Parar',
        syncBothOpen: 'Os dois aparelhos têm de estar abertos ao mesmo tempo.',
        syncFailed: (reason: string) => `Não resultou: ${reason}`,
    },
    nl: {
        metaTitle: 'Over deze pagina',
        metaSubtitle: 'De vraag waar hij op antwoordt, en waar de cijfers vandaan komen.',
        taskLabel: 'Vraag',
        gapsTitle: 'Waar dit op berust',
        gapsSubtitle: 'Waar de informatie vandaan komt en hoe ver je erop kunt bouwen.',
        gapsAskTitle: 'Beantwoord dit, dan wordt de volgende versie beter',
        gapsAskText: 'Schrijf de antwoorden gewoon in de chat — ze gaan de repo in en de pagina wordt opnieuw gebouwd.',
        gapsCopied: 'Vragen gekopieerd',
        gapsCopyFailed: 'Kopiëren is niet gelukt',
        severityMissing: 'ontbreekt',
        severityAssumed: 'aangenomen',
        severityStale: 'verouderd',
        severityMissingHint: 'Hierover staat niets in de repo.',
        severityAssumedHint: 'Hier is een aanname gebruikt.',
        severityStaleHint: 'Opgeslagen, maar misschien niet meer actueel.',
        sourcesTitle: 'Bronnen',
        share: 'Delen',
        themeLight: 'Licht thema',
        themeDark: 'Donker thema',
        confirmTitle: 'Zeker weten?',
        confirmYes: 'Ja, doen',
        confirmNo: 'Annuleren',
        close: 'Sluiten',
        shareTitle: 'Deze pagina delen',
        copyLink: 'Link kopiëren',
        linkCopied: 'Link gekopieerd',
        copyFailed: 'Kopiëren is niet gelukt',
        shareLocalFile: 'Deze pagina draait als lokaal bestand. De link hieronder wijst naar je eigen schijf — alleen de gepubliceerde versie is te delen.',
        shareTooLongForQr: 'Het adres is te lang voor een QR-code. De link werkt gewoon.',
        shareLinkIsTheLock: 'De link is het slot: wie hem heeft, kan de pagina lezen.',
        shareNative: 'Delen…',
        shareFailed: 'Delen is mislukt',
        copyUnsupported: 'Deze browser kan niet naar het klembord kopiëren',
        scanWithPhone: 'Scan met de camera van je telefoon',
        checkedToday: () => 'vandaag gecontroleerd',
        checkedDaysAgo: (days: number) => `${days} dagen geleden`,
        assumedInstead: 'In plaats daarvan aangenomen: ',
        wobbles: 'Wat dat verschuift: ',
        asOf: 'Stand van',
        why: 'Waarom',
        criterion: 'Criterium',
        must: 'Must',
        out: 'valt af',
        mustFailed: 'Aan een must-criterium is niet voldaan.',
        more: 'Meer',
        nothingFound: 'Niets gevonden',
        noEntries: 'Geen items',
        noCoordinates: 'Geen coördinaten',
        mapSketch: 'Kaartschets',
        pickOnMap: 'Kies een punt op de kaart',
        latitude: 'Breedte',
        longitude: 'Lengte',
        openInMaps: 'Openen in Maps',
        qrTooLong: 'Te lang voor een QR-code.',
        qrFor: (value: string) => 'QR-code voor ' + value,
        ingredients: 'Ingrediënten',
        method: 'Bereiding',
        recipeImageMissing: 'Foto ontbreekt — elk recept heeft er een nodig',
        toShop: 'Naar de winkel',
        owned: 'heb ik',
        topPick: 'Beste keuze',
        perNight: 'per nacht',
        nights: (n: number) => n + (n === 1 ? ' nacht' : ' nachten'),
        playerLoading: 'Speler laadt …',
        checkedAgainstOriginal: 'Bij het origineel nagekeken.',
        notChecked: 'Niet nagekeken — kan fout zijn.',
        copyQuestions: 'Vragen kopiëren',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Je gegevens bewaren en meenemen',
        syncIntro: 'Alles wat deze pagina onthoudt staat in deze browser. Hier haal je het eruit, zet je het terug, of breng je een tweede apparaat op dezelfde stand.',
        syncFileTitle: 'Bestand',
        syncFileNote: 'Een JSON-bestand op je eigen schijf. Geen account, geen verbinding, en over tien jaar gaat het nog open. Inladen voegt samen in plaats van te vervangen.',
        syncExport: 'Opslaan als bestand',
        syncImport: 'Uit bestand laden',
        syncImported: (rows: number) => `${rows} items geladen`,
        syncCloudTitle: 'Cloudopslag',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Synchroniseert naar een verborgen map die alleen van deze pagina is — de rest van je bestanden blijft buiten beeld. Het loopt zolang de pagina open staat; na ongeveer een uur verloopt de aanmelding en verbind je opnieuw.',
        syncConnect: 'Verbinden',
        syncDisconnect: 'Verbreken',
        syncConnected: 'Verbonden',
        syncNeedsClientId: 'Je hebt je eigen OAuth-client-id van de aanbieder nodig — gratis, één keer aanmaken. Plak hem hier; hij blijft in deze browser en gaat nergens heen.',
        syncP2PTitle: 'P2P naar een ander apparaat',
        syncP2PNote: 'De apparaten praten rechtstreeks met elkaar; er gaat niets via een server. De code is meteen het wachtwoord: wie hem heeft, synchroniseert met jou. Geef hem alleen aan wie je wilt.',
        syncCode: 'Jouw code',
        syncClientIdLabel: 'OAuth-client-id',
        syncSaveAndConnect: 'Opslaan en verbinden',
        syncJoinCode: 'De code van iemand anders',
        syncJoinHint: 'Plak hier de code die je hebt gekregen. Zolang hier iets staat, wordt die gebruikt in plaats van je eigen code.',
        syncNewCode: 'Nieuwe code',
        syncCopy: 'Kopiëren',
        syncCopied: 'Gekopieerd',
        syncStart: 'Starten',
        syncStop: 'Stoppen',
        syncBothOpen: 'Beide apparaten moeten tegelijk open staan.',
        syncFailed: (reason: string) => `Dat is niet gelukt: ${reason}`,
    },
    pl: {
        metaTitle: 'O tej stronie',
        metaSubtitle: 'Prośba, z której powstała, i skąd pochodzą dane.',
        taskLabel: 'Prośba',
        gapsTitle: 'Na czym to się opiera',
        gapsSubtitle: 'Skąd pochodzą informacje i na ile można na nich polegać.',
        gapsAskTitle: 'Odpowiedz na to, a kolejna wersja będzie lepsza',
        gapsAskText: 'Po prostu wpisz odpowiedzi na czacie — trafią do repozytorium, a strona zostanie zbudowana na nowo.',
        gapsCopied: 'Pytania skopiowane',
        gapsCopyFailed: 'Kopiowanie się nie udało',
        severityMissing: 'brakuje',
        severityAssumed: 'założone',
        severityStale: 'nieaktualne',
        severityMissingHint: 'W repozytorium nic o tym nie ma.',
        severityAssumedHint: 'Użyto tutaj założenia.',
        severityStaleHint: 'Zapisane, ale może być już nieaktualne.',
        sourcesTitle: 'Źródła',
        share: 'Udostępnij',
        themeLight: 'Jasny motyw',
        themeDark: 'Ciemny motyw',
        confirmTitle: 'Na pewno?',
        confirmYes: 'Tak, zrób to',
        confirmNo: 'Anuluj',
        close: 'Zamknij',
        shareTitle: 'Udostępnij tę stronę',
        copyLink: 'Kopiuj link',
        linkCopied: 'Link skopiowany',
        copyFailed: 'Kopiowanie się nie udało',
        shareLocalFile: 'Ta strona działa jako plik lokalny. Link poniżej wskazuje na twój dysk — udostępnić można dopiero wersję opublikowaną.',
        shareTooLongForQr: 'Adres jest za długi na kod QR. Link i tak działa.',
        shareLinkIsTheLock: 'Link jest zamkiem: kto go ma, może przeczytać stronę.',
        shareNative: 'Udostępnij…',
        shareFailed: 'Udostępnianie się nie powiodło',
        copyUnsupported: 'Ta przeglądarka nie potrafi kopiować do schowka',
        scanWithPhone: 'Zeskanuj aparatem telefonu',
        checkedToday: () => 'sprawdzone dzisiaj',
        checkedDaysAgo: (days: number) => `${days} dni temu`,
        assumedInstead: 'Przyjęto zamiast tego: ',
        wobbles: 'Co to przesuwa: ',
        asOf: 'Stan na',
        why: 'Dlaczego',
        criterion: 'Kryterium',
        must: 'Konieczne',
        out: 'odpada',
        mustFailed: 'Kryterium konieczne nie jest spełnione.',
        more: 'Więcej',
        nothingFound: 'Nic nie znaleziono',
        noEntries: 'Brak wpisów',
        noCoordinates: 'Brak współrzędnych',
        mapSketch: 'Szkic mapy',
        pickOnMap: 'Wybierz punkt na mapie',
        latitude: 'Szerokość',
        longitude: 'Długość',
        openInMaps: 'Otwórz w Maps',
        qrTooLong: 'Za długie na kod QR.',
        qrFor: (value: string) => 'Kod QR dla ' + value,
        ingredients: 'Składniki',
        method: 'Przygotowanie',
        recipeImageMissing: 'Brakuje zdjęcia — każdy przepis go potrzebuje',
        toShop: 'Do sklepu',
        owned: 'mam',
        topPick: 'Najlepszy wybór',
        perNight: 'za noc',
        nights: (n: number) => n + (n === 1 ? ' noc' : (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) ? ' noce' : ' nocy')),
        playerLoading: 'Odtwarzacz się ładuje …',
        checkedAgainstOriginal: 'Sprawdzone w oryginale.',
        notChecked: 'Niesprawdzone — może być błędne.',
        copyQuestions: 'Kopiuj pytania',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Zapisz i przenieś swoje dane',
        syncIntro: 'Wszystko, co ta strona pamięta, leży w tej przeglądarce. Tutaj to wyjmiesz, wgrasz z powrotem albo ustawisz drugie urządzenie na ten sam stan.',
        syncFileTitle: 'Plik',
        syncFileNote: 'Plik JSON na twoim dysku. Bez konta, bez połączenia, i za dziesięć lat nadal się otworzy. Wczytanie scala dane, a nie zastępuje.',
        syncExport: 'Zapisz jako plik',
        syncImport: 'Wczytaj z pliku',
        syncImported: (rows: number) => `Wczytano wpisów: ${rows}`,
        syncCloudTitle: 'Dysk w chmurze',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Synchronizuje do ukrytego folderu, który należy tylko do tej strony — reszta twoich plików pozostaje poza zasięgiem. Działa, dopóki strona jest otwarta; logowanie wygasa po mniej więcej godzinie i łączysz się ponownie.',
        syncConnect: 'Połącz',
        syncDisconnect: 'Rozłącz',
        syncConnected: 'Połączono',
        syncNeedsClientId: 'Potrzebujesz własnego identyfikatora klienta OAuth od dostawcy — za darmo, zakładany raz. Wklej go tutaj; zostaje w tej przeglądarce i nigdzie nie jest wysyłany.',
        syncP2PTitle: 'P2P na inne urządzenie',
        syncP2PNote: 'Urządzenia rozmawiają ze sobą bezpośrednio; nic nie idzie przez serwer. Kod jest zarazem hasłem: kto go ma, synchronizuje się z tobą. Przekaż go tylko komu chcesz.',
        syncCode: 'Twój kod',
        syncClientIdLabel: 'Identyfikator klienta OAuth',
        syncSaveAndConnect: 'Zapisz i połącz',
        syncJoinCode: 'Kod od kogoś innego',
        syncJoinHint: 'Wklej tutaj kod, który dostałeś. Dopóki coś tu jest, używany jest on zamiast twojego.',
        syncNewCode: 'Nowy kod',
        syncCopy: 'Kopiuj',
        syncCopied: 'Skopiowano',
        syncStart: 'Start',
        syncStop: 'Stop',
        syncBothOpen: 'Oba urządzenia muszą być wtedy otwarte jednocześnie.',
        syncFailed: (reason: string) => `Nie udało się: ${reason}`,
    },
    tr: {
        metaTitle: 'Bu sayfa hakkında',
        metaSubtitle: 'Dayandığı istek ve verilerin nereden geldiği.',
        taskLabel: 'İstek',
        gapsTitle: 'Neye dayanıyor',
        gapsSubtitle: 'Bilgilerin nereden geldiği ve ne kadar güvenilir olduğu.',
        gapsAskTitle: 'Bunları yanıtla, bir sonraki sürüm daha iyi olsun',
        gapsAskText: 'Yanıtları sohbete yaz — depoya işlenir ve sayfa yeniden oluşturulur.',
        gapsCopied: 'Sorular kopyalandı',
        gapsCopyFailed: 'Kopyalama olmadı',
        severityMissing: 'eksik',
        severityAssumed: 'varsayıldı',
        severityStale: 'güncel değil',
        severityMissingHint: 'Depoda bununla ilgili bir şey yok.',
        severityAssumedHint: 'Burada bir varsayım kullanıldı.',
        severityStaleHint: 'Kayıtlı ama artık güncel olmayabilir.',
        sourcesTitle: 'Kaynaklar',
        share: 'Paylaş',
        themeLight: 'Açık tema',
        themeDark: 'Koyu tema',
        confirmTitle: 'Emin misin?',
        confirmYes: 'Evet, yap',
        confirmNo: 'Vazgeç',
        close: 'Kapat',
        shareTitle: 'Bu sayfayı paylaş',
        copyLink: 'Bağlantıyı kopyala',
        linkCopied: 'Bağlantı kopyalandı',
        copyFailed: 'Kopyalama olmadı',
        shareLocalFile: 'Bu sayfa yerel bir dosya olarak çalışıyor. Aşağıdaki bağlantı kendi diskini gösteriyor — yalnızca yayımlanmış sürüm paylaşılabilir.',
        shareTooLongForQr: 'Adres bir QR kod için fazla uzun. Bağlantı yine de çalışıyor.',
        shareLinkIsTheLock: 'Bağlantı kilidin kendisi: elinde olan sayfayı okuyabilir.',
        shareNative: 'Paylaş…',
        shareFailed: 'Paylaşma başarısız',
        copyUnsupported: 'Bu tarayıcı panoya kopyalayamıyor',
        scanWithPhone: 'Telefon kamerasıyla tarat',
        checkedToday: () => 'bugün kontrol edildi',
        checkedDaysAgo: (days: number) => `${days} gün önce`,
        assumedInstead: 'Onun yerine varsayıldı: ',
        wobbles: 'Bunun oynattığı: ',
        asOf: 'Tarih',
        why: 'Neden',
        criterion: 'Ölçüt',
        must: 'Şart',
        out: 'elendi',
        mustFailed: 'Şart olan bir ölçüt karşılanmıyor.',
        more: 'Daha fazla',
        nothingFound: 'Bir şey bulunamadı',
        noEntries: 'Kayıt yok',
        noCoordinates: 'Koordinat yok',
        mapSketch: 'Harita krokisi',
        pickOnMap: 'Haritada bir nokta seç',
        latitude: 'Enlem',
        longitude: 'Boylam',
        openInMaps: 'Maps’te aç',
        qrTooLong: 'QR kod için fazla uzun.',
        qrFor: (value: string) => value + ' için QR kod',
        ingredients: 'Malzemeler',
        method: 'Yapılışı',
        recipeImageMissing: 'Fotoğraf eksik — her tarifin birine ihtiyacı var',
        toShop: 'Mağazaya',
        owned: 'bende var',
        topPick: 'En iyi seçim',
        perNight: 'gecelik',
        nights: (n: number) => n + ' gece',
        playerLoading: 'Oynatıcı yükleniyor …',
        checkedAgainstOriginal: 'Aslına bakıldı.',
        notChecked: 'Bakılmadı — yanlış olabilir.',
        copyQuestions: 'Soruları kopyala',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Verilerini yedekle ve taşı',
        syncIntro: 'Bu sayfanın hatırladığı her şey bu tarayıcıda duruyor. Buradan dışarı alırsın, geri koyarsın ya da ikinci bir cihazı aynı hizaya getirirsin.',
        syncFileTitle: 'Dosya',
        syncFileNote: 'Kendi diskinde bir JSON dosyası. Hesap yok, bağlantı yok, on yıl sonra da açılır. Yüklemek değiştirmez, birleştirir.',
        syncExport: 'Dosya olarak kaydet',
        syncImport: 'Dosyadan yükle',
        syncImported: (rows: number) => `${rows} kayıt yüklendi`,
        syncCloudTitle: 'Bulut depolama',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Yalnızca bu sayfaya ait gizli bir klasöre eşitler — diğer dosyaların görünmez kalır. Sayfa açık kaldığı sürece çalışır; oturum aşağı yukarı bir saatte düşer, yeniden bağlanırsın.',
        syncConnect: 'Bağlan',
        syncDisconnect: 'Bağlantıyı kes',
        syncConnected: 'Bağlandı',
        syncNeedsClientId: 'Sağlayıcıdan kendi OAuth istemci kimliğin gerekiyor — ücretsiz, bir kez oluşturuluyor. Buraya yapıştır; bu tarayıcıda kalır ve hiçbir yere gönderilmez.',
        syncP2PTitle: 'Başka bir cihaza P2P',
        syncP2PNote: 'Cihazlar doğrudan birbiriyle konuşur; hiçbir şey sunucudan geçmez. Kod aynı zamanda paroladır: kimde varsa seninle eşitlenir. Yalnızca istediğin kişiye ver.',
        syncCode: 'Senin kodun',
        syncClientIdLabel: 'OAuth istemci kimliği',
        syncSaveAndConnect: 'Kaydet ve bağlan',
        syncJoinCode: 'Başkasının kodu',
        syncJoinHint: 'Sana verilen kodu buraya yapıştır. Burada bir şey oldukça seninki yerine o kullanılır.',
        syncNewCode: 'Yeni kod',
        syncCopy: 'Kopyala',
        syncCopied: 'Kopyalandı',
        syncStart: 'Başlat',
        syncStop: 'Durdur',
        syncBothOpen: 'İki cihazın da aynı anda açık olması gerekir.',
        syncFailed: (reason: string) => `Olmadı: ${reason}`,
    },
    ru: {
        metaTitle: 'Об этой странице',
        metaSubtitle: 'Запрос, на который она отвечает, и откуда взяты данные.',
        taskLabel: 'Запрос',
        gapsTitle: 'На чём это основано',
        gapsSubtitle: 'Откуда взяты сведения и насколько на них можно положиться.',
        gapsAskTitle: 'Ответь на это, и следующая версия станет лучше',
        gapsAskText: 'Просто напиши ответы в чат — они попадут в репозиторий, и страница будет собрана заново.',
        gapsCopied: 'Вопросы скопированы',
        gapsCopyFailed: 'Скопировать не удалось',
        severityMissing: 'нет данных',
        severityAssumed: 'предположение',
        severityStale: 'устарело',
        severityMissingHint: 'В репозитории об этом ничего нет.',
        severityAssumedHint: 'Здесь использовано предположение.',
        severityStaleHint: 'Сохранено, но, возможно, уже неактуально.',
        sourcesTitle: 'Источники',
        share: 'Поделиться',
        themeLight: 'Светлая тема',
        themeDark: 'Тёмная тема',
        confirmTitle: 'Точно?',
        confirmYes: 'Да, сделать',
        confirmNo: 'Отмена',
        close: 'Закрыть',
        shareTitle: 'Поделиться страницей',
        copyLink: 'Скопировать ссылку',
        linkCopied: 'Ссылка скопирована',
        copyFailed: 'Скопировать не удалось',
        shareLocalFile: 'Страница открыта как локальный файл. Ссылка ниже ведёт на твой диск — поделиться можно только опубликованной версией.',
        shareTooLongForQr: 'Адрес слишком длинный для QR-кода. Ссылка всё равно работает.',
        shareLinkIsTheLock: 'Ссылка и есть замок: у кого она есть, тот прочитает страницу.',
        shareNative: 'Поделиться…',
        shareFailed: 'Поделиться не удалось',
        copyUnsupported: 'Этот браузер не может копировать в буфер обмена',
        scanWithPhone: 'Отсканируй камерой телефона',
        checkedToday: () => 'проверено сегодня',
        checkedDaysAgo: (days: number) => `${days} дн. назад`,
        assumedInstead: 'Взято как допущение: ',
        wobbles: 'Что от этого смещается: ',
        asOf: 'На дату',
        why: 'Почему',
        criterion: 'Критерий',
        must: 'Обязательно',
        out: 'выбывает',
        mustFailed: 'Обязательный критерий не выполнен.',
        more: 'Ещё',
        nothingFound: 'Ничего не найдено',
        noEntries: 'Нет записей',
        noCoordinates: 'Нет координат',
        mapSketch: 'Схема карты',
        pickOnMap: 'Выбери точку на карте',
        latitude: 'Широта',
        longitude: 'Долгота',
        openInMaps: 'Открыть в Maps',
        qrTooLong: 'Слишком длинно для QR-кода.',
        qrFor: (value: string) => 'QR-код для ' + value,
        ingredients: 'Ингредиенты',
        method: 'Приготовление',
        recipeImageMissing: 'Нет фотографии — она нужна каждому рецепту',
        toShop: 'В магазин',
        owned: 'уже есть',
        topPick: 'Лучший вариант',
        perNight: 'за ночь',
        nights: (n: number) => {
            const t = n % 10;
            const h = n % 100;
            if (t === 1 && h !== 11) return n + ' ночь';
            if (t >= 2 && t <= 4 && (h < 12 || h > 14)) return n + ' ночи';
            return n + ' ночей';
        },
        playerLoading: 'Плеер загружается …',
        checkedAgainstOriginal: 'Сверено с оригиналом.',
        notChecked: 'Не сверено — может быть неверно.',
        copyQuestions: 'Скопировать вопросы',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'Сохранить и перенести данные',
        syncIntro: 'Всё, что помнит эта страница, лежит в этом браузере. Отсюда можно забрать это, вернуть обратно или подтянуть второе устройство к тому же состоянию.',
        syncFileTitle: 'Файл',
        syncFileNote: 'JSON-файл на твоём диске. Без учётной записи, без связи — и через десять лет он всё ещё откроется. Загрузка объединяет, а не заменяет.',
        syncExport: 'Сохранить в файл',
        syncImport: 'Загрузить из файла',
        syncImported: (rows: number) => `Загружено записей: ${rows}`,
        syncCloudTitle: 'Облачное хранилище',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'Синхронизирует в скрытую папку, принадлежащую только этой странице, — остальные твои файлы остаются вне поля зрения. Работает, пока страница открыта; вход истекает примерно через час, и ты подключаешься заново.',
        syncConnect: 'Подключить',
        syncDisconnect: 'Отключить',
        syncConnected: 'Подключено',
        syncNeedsClientId: 'Нужен твой собственный OAuth-идентификатор клиента у провайдера — бесплатно, создаётся один раз. Вставь его сюда: он останется в этом браузере и никуда не уйдёт.',
        syncP2PTitle: 'P2P на другое устройство',
        syncP2PNote: 'Устройства говорят напрямую друг с другом; через сервер ничего не идёт. Код — он же пароль: у кого он есть, тот с тобой и синхронизируется. Передавай его только тому, кому собирался.',
        syncCode: 'Твой код',
        syncClientIdLabel: 'OAuth-идентификатор клиента',
        syncSaveAndConnect: 'Сохранить и подключить',
        syncJoinCode: 'Чужой код',
        syncJoinHint: 'Вставь сюда код, который тебе дали. Пока здесь что-то есть, используется он, а не твой.',
        syncNewCode: 'Новый код',
        syncCopy: 'Скопировать',
        syncCopied: 'Скопировано',
        syncStart: 'Запустить',
        syncStop: 'Остановить',
        syncBothOpen: 'Оба устройства должны быть открыты одновременно.',
        syncFailed: (reason: string) => `Не получилось: ${reason}`,
    },
    zh: {
        metaTitle: '关于本页',
        metaSubtitle: '本页回应的请求，以及数据的来源。',
        taskLabel: '请求',
        gapsTitle: '依据是什么',
        gapsSubtitle: '这些信息从哪里来，以及可信到什么程度。',
        gapsAskTitle: '回答这些问题，下一版会更好',
        gapsAskText: '直接把答案写在对话里——它们会存进仓库，页面会重新生成。',
        gapsCopied: '问题已复制',
        gapsCopyFailed: '复制没有成功',
        severityMissing: '缺失',
        severityAssumed: '假设',
        severityStale: '已过时',
        severityMissingHint: '仓库里没有相关记录。',
        severityAssumedHint: '这里用了一个假设。',
        severityStaleHint: '已保存，但可能不再是最新的。',
        sourcesTitle: '来源',
        share: '分享',
        themeLight: '浅色主题',
        themeDark: '深色主题',
        confirmTitle: '确定吗？',
        confirmYes: '确定',
        confirmNo: '取消',
        close: '关闭',
        shareTitle: '分享此页',
        copyLink: '复制链接',
        linkCopied: '链接已复制',
        copyFailed: '复制没有成功',
        shareLocalFile: '此页正以本地文件运行。下面的链接指向你自己的硬盘——只有已发布的版本才能分享。',
        shareTooLongForQr: '这个网址对二维码来说太长了。链接本身仍然可用。',
        shareLinkIsTheLock: '链接就是那把锁：谁拿到它，谁就能读这一页。',
        shareNative: '分享…',
        shareFailed: '分享失败',
        copyUnsupported: '此浏览器无法复制到剪贴板',
        scanWithPhone: '用手机相机扫描',
        checkedToday: () => '今天已核对',
        checkedDaysAgo: (days: number) => `${days} 天前`,
        assumedInstead: '改用了这个假设：',
        wobbles: '因此会变动的：',
        asOf: '截至',
        why: '原因',
        criterion: '条件',
        must: '必须',
        out: '淘汰',
        mustFailed: '有一项必须条件没有满足。',
        more: '更多',
        nothingFound: '没有找到',
        noEntries: '没有条目',
        noCoordinates: '没有坐标',
        mapSketch: '地图示意',
        pickOnMap: '在地图上选一个点',
        latitude: '纬度',
        longitude: '经度',
        openInMaps: '在地图中打开',
        qrTooLong: '太长，无法生成二维码。',
        qrFor: (value: string) => value + ' 的二维码',
        ingredients: '食材',
        method: '做法',
        recipeImageMissing: '缺少图片——每份食谱都需要一张',
        toShop: '前往商店',
        owned: '已拥有',
        topPick: '首选',
        perNight: '每晚',
        nights: (n: number) => n + ' 晚',
        playerLoading: '播放器加载中 …',
        checkedAgainstOriginal: '已与原始资料核对。',
        notChecked: '未核对——可能有误。',
        copyQuestions: '复制问题',
        /* --- data sync ---------------------------------------------- */
        syncTitle: '备份并转移你的数据',
        syncIntro: '这个页面记住的一切都在这个浏览器里。在这里你可以把它取出来、放回去，或者让第二台设备跟上同样的进度。',
        syncFileTitle: '文件',
        syncFileNote: '一个存在你自己硬盘上的 JSON 文件。不需要账号，不需要联网，十年后依然打得开。载入时是合并，不是覆盖。',
        syncExport: '保存为文件',
        syncImport: '从文件载入',
        syncImported: (rows: number) => `已载入 ${rows} 条`,
        syncCloudTitle: '云端存储',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: '同步到一个只属于这个页面的隐藏文件夹——你其余的文件始终看不到。页面开着就一直同步；登录大约一小时后过期，再连一次即可。',
        syncConnect: '连接',
        syncDisconnect: '断开',
        syncConnected: '已连接',
        syncNeedsClientId: '你需要在对应服务那里申请一个自己的 OAuth 客户端 ID——免费，只需申请一次。把它粘贴在这里；它只留在这个浏览器里，不会发往任何地方。',
        syncP2PTitle: 'P2P 连到另一台设备',
        syncP2PNote: '两台设备直接对话，数据不经过任何服务器。这串代码同时就是密码：拿到它的人就能和你同步，只给你真正想给的人。',
        syncCode: '你的代码',
        syncClientIdLabel: 'OAuth 客户端 ID',
        syncSaveAndConnect: '保存并连接',
        syncJoinCode: '别人的代码',
        syncJoinHint: '把别人给你的代码粘贴在这里。只要这里有内容，就用它，而不是你自己的。',
        syncNewCode: '换一个',
        syncCopy: '复制',
        syncCopied: '已复制',
        syncStart: '开始',
        syncStop: '停止',
        syncBothOpen: '两台设备必须同时开着。',
        syncFailed: (reason: string) => `没有成功：${reason}`,
    },
    ja: {
        metaTitle: 'このページについて',
        metaSubtitle: 'もとになった依頼と、数字の出どころ。',
        taskLabel: '依頼',
        gapsTitle: '何にもとづいているか',
        gapsSubtitle: '情報の出どころと、どこまで信頼できるか。',
        gapsAskTitle: 'これに答えると次の版がよくなります',
        gapsAskText: '答えをチャットに書くだけで大丈夫です — リポジトリに記録され、ページが作り直されます。',
        gapsCopied: '質問をコピーしました',
        gapsCopyFailed: 'コピーできませんでした',
        severityMissing: '未記録',
        severityAssumed: '仮定',
        severityStale: '古い可能性',
        severityMissingHint: 'これについてはリポジトリに何もありません。',
        severityAssumedHint: 'ここでは仮定を使っています。',
        severityStaleHint: '保存済みですが、最新ではないかもしれません。',
        sourcesTitle: '出典',
        share: '共有',
        themeLight: 'ライトテーマ',
        themeDark: 'ダークテーマ',
        confirmTitle: '本当によろしいですか？',
        confirmYes: 'はい、実行',
        confirmNo: 'キャンセル',
        close: '閉じる',
        shareTitle: 'このページを共有',
        copyLink: 'リンクをコピー',
        linkCopied: 'リンクをコピーしました',
        copyFailed: 'コピーできませんでした',
        shareLocalFile: 'このページはローカルファイルとして開かれています。下のリンクは自分のディスクを指しています — 共有できるのは公開版だけです。',
        shareTooLongForQr: 'アドレスが長すぎて QR コードにできません。リンク自体は使えます。',
        shareLinkIsTheLock: 'リンクが鍵そのものです。持っている人はこのページを読めます。',
        shareNative: '共有…',
        shareFailed: '共有できませんでした',
        copyUnsupported: 'このブラウザではクリップボードにコピーできません',
        scanWithPhone: 'スマホのカメラで読み取ってください',
        checkedToday: () => '今日確認',
        checkedDaysAgo: (days: number) => `${days} 日前`,
        assumedInstead: '代わりに置いた仮定：',
        wobbles: 'それで変わるところ：',
        asOf: '時点',
        why: '理由',
        criterion: '条件',
        must: '必須',
        out: '除外',
        mustFailed: '必須条件を満たしていません。',
        more: 'もっと見る',
        nothingFound: '見つかりませんでした',
        noEntries: '項目がありません',
        noCoordinates: '座標がありません',
        mapSketch: '地図の概略',
        pickOnMap: '地図上で地点を選ぶ',
        latitude: '緯度',
        longitude: '経度',
        openInMaps: 'マップで開く',
        qrTooLong: '長すぎて QR コードにできません。',
        qrFor: (value: string) => value + ' の QR コード',
        ingredients: '材料',
        method: '作り方',
        recipeImageMissing: '写真がありません — レシピには必ず一枚',
        toShop: 'ショップへ',
        owned: '持っている',
        topPick: 'いちおし',
        perNight: '1泊あたり',
        nights: (n: number) => n + '泊',
        playerLoading: 'プレーヤーを読み込み中 …',
        checkedAgainstOriginal: '原典で確認しました。',
        notChecked: '未確認 — 間違っている可能性があります。',
        copyQuestions: '質問をコピー',
        /* --- data sync ---------------------------------------------- */
        syncTitle: 'データを保存して持ち出す',
        syncIntro: 'このページが覚えていることは、すべてこのブラウザの中にあります。ここから取り出したり、戻したり、もう一台の端末を同じ状態にそろえたりできます。',
        syncFileTitle: 'ファイル',
        syncFileNote: '自分のディスクに置く JSON ファイルです。アカウントも接続もいらず、10 年後でも開けます。読み込みは置き換えではなく、統合です。',
        syncExport: 'ファイルとして保存',
        syncImport: 'ファイルから読み込む',
        syncImported: (rows: number) => `${rows} 件を読み込みました`,
        syncCloudTitle: 'クラウド保存',
        syncGoogleTitle: 'Google Drive',
        syncOneDriveTitle: 'OneDrive',
        syncCloudNote: 'このページ専用の隠しフォルダーに同期します — ほかのファイルは見えないままです。ページを開いているあいだ動き、ログインは 1 時間ほどで切れるので、そのときは接続し直してください。',
        syncConnect: '接続',
        syncDisconnect: '切断',
        syncConnected: '接続済み',
        syncNeedsClientId: '各サービスで自分の OAuth クライアント ID を取る必要があります — 無料で、一度作るだけです。ここに貼り付けてください。このブラウザの中だけに残り、どこにも送られません。',
        syncP2PTitle: 'P2P で別の端末へ',
        syncP2PNote: '端末どうしが直接やり取りし、サーバーは一切通りません。このコードはそのまま合鍵です。持っている人はあなたと同期できるので、渡す相手は選んでください。',
        syncCode: 'あなたのコード',
        syncClientIdLabel: 'OAuth クライアント ID',
        syncSaveAndConnect: '保存して接続',
        syncJoinCode: '相手のコード',
        syncJoinHint: '受け取ったコードをここに貼り付けてください。ここに何か入っているあいだは、自分のコードではなくそちらが使われます。',
        syncNewCode: '新しいコード',
        syncCopy: 'コピー',
        syncCopied: 'コピーしました',
        syncStart: '開始',
        syncStop: '停止',
        syncBothOpen: '2 台とも同時に開いている必要があります。',
        syncFailed: (reason: string) => `うまくいきませんでした: ${reason}`,
    },
};
