/**
 * The service worker, generated at build time.
 *
 * A manifest alone does not make a page installable — Chromium wants a service
 * worker with a fetch handler before it offers the install prompt. And a page
 * whose whole point is that it needs no server should keep working when there
 * is none, so this is a real offline cache rather than a formality.
 *
 * What goes where:
 *
 * - **Precached** on install: the shell (HTML, JS, CSS), the icon, the manifest
 *   and all five sounds (216 KB together). A posture watcher whose alarm is
 *   silent offline is not one.
 * - **Cached on first use**: the pose model under `mp/`. It is ~17 MB, so
 *   forcing it through the install step would mean a page that appears to hang
 *   on first visit. It lands in the cache the first time the camera runs.
 *
 * The precache list is written from the real bundle, so it carries the hashed
 * filenames and a new build invalidates the old cache by name.
 */

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/** Served as-is out of `public/`, so Vite's bundle does not list them. */
const STATIC = [
    'icon.svg',
    'manifest.webmanifest',
    'snd/furz.mp3',
    'snd/knacken.mp3',
    'snd/raeuspern.mp3',
    'snd/rimshot.mp3',
    'snd/schrei.mp3',
];

const worker = (version, files) => `/* Generated by scripts/pwa.mjs — do not edit. */
const CACHE = 'deshrimp-${version}';
const SHELL = ${JSON.stringify(files, null, 4)};

self.addEventListener('install', (event) => {
    // Individually, so one missing file cannot fail the whole install.
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        await Promise.all(SHELL.map((f) => cache.add(f).catch(() => {})));
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const names = await caches.keys();
        await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // A navigation always gets the shell: this is one page, and offline it is
    // still that page.
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            try {
                return await fetch(request);
            } catch {
                return (await caches.match('./index.html')) || Response.error();
            }
        })());
        return;
    }

    // Everything else: serve from cache when it is there, otherwise fetch and
    // keep a copy. This is what pulls the pose model in on first use.
    event.respondWith((async () => {
        const hit = await caches.match(request);
        if (hit) return hit;
        try {
            const response = await fetch(request);
            if (response.ok && response.type === 'basic') {
                const cache = await caches.open(CACHE);
                void cache.put(request, response.clone());
            }
            return response;
        } catch {
            return Response.error();
        }
    })());
});
`;

export default function pwa() {
    return {
        name: 'deshrimp-pwa',
        apply: 'build',
        generateBundle(_options, bundle) {
            const built = Object.values(bundle)
                .map((chunk) => chunk.fileName)
                .filter((name) => name.endsWith('.js') || name.endsWith('.css'));

            // The bundle hashes change whenever anything does, so hashing the
            // list is enough to name a cache generation.
            const version = readFileSync(resolve(here, '..', 'package.json'), 'utf8')
                && [...built, ...STATIC].join('|').split('').reduce(
                    (h, c) => (Math.imul(31, h) + c.charCodeAt(0)) | 0, 7,
                ).toString(36).replace('-', 'z');

            const files = ['./index.html', ...built.map((f) => `./${f}`), ...STATIC.map((f) => `./${f}`)];
            this.emitFile({ type: 'asset', fileName: 'sw.js', source: worker(version, files) });
        },
    };
}
