/**
 * The service worker, generated at build time.
 *
 * A manifest alone does not make a page installable - Chromium wants a service
 * worker with a fetch handler before it offers the install prompt. And a page
 * whose whole point is that it needs no server should keep working when there
 * is none, so this is a real offline cache rather than a formality.
 *
 * Two caches, because the two halves expire for different reasons
 * ---------------------------------------------------------------
 * - **`deshrimp-shell-<bundle>`** is precached on install: the shell (the root
 *   HTML *and* the thirteen per-language pages, which are the same page with
 *   another head and another prerendered block, so they are a few KB each), the
 *   JS and CSS, the brand type, the icon and mark, the manifest and all six
 *   sounds. A posture watcher whose alarm is silent offline is not one, and an
 *   interface that falls back to the system sans offline is one that looks
 *   broken on the day the network is gone. Its name carries the bundle hashes,
 *   so every deploy retires the previous one.
 * - **`deshrimp-model-<pin>`** fills on first use with the pose model under
 *   `mp/`. It is ~17 MB, so forcing it through the install step would mean a
 *   page that appears to hang on first visit. It lands in the cache the first
 *   time the camera runs.
 *
 * Keeping them apart is the whole point of the split. `mp/` used to live in the
 * one versioned cache, which `activate` deletes by name on every deploy, so a
 * typo fixed in a German string cost every returning visitor the seventeen
 * megabytes again. The model does not change when the app does: it changes when
 * `scripts/pose-model.sha256` does, and that file is what names this cache. A
 * deploy that leaves the pin alone leaves the bytes alone.
 *
 * So the name is the hash, in the only sense that is worth anything here: it is
 * derived from the digests the build already refuses to ship without, which
 * means a changed model cannot keep the old cache and an unchanged one cannot
 * lose it. (The deploy that introduces the split still costs existing installs
 * one download, because their copy is sitting in the shell cache that is about
 * to be retired. It is the last one.)
 *
 * The precache list is written from the real bundle, so it carries the hashed
 * filenames and a new build invalidates the old cache by name.
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LANGS } from './seo.mjs';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The per-language pages (`de.html`, `ja.html`, ...). `scripts/seo.mjs` writes
 * them after the bundle, so they are not in it either - and a site that is one
 * URL per language must be able to open the URL that was installed, not only
 * the root one, when the network is gone.
 */
const PAGES = LANGS.map((l) => `./${l}.html`);

/** Served as-is out of `public/`, so Vite's bundle does not list them. */
const STATIC = [
    'icon.svg',
    'icon-maskable.svg',
    'manifest.webmanifest',
    'brand/logo.svg',
    'brand/mark.svg',
    'snd/ahem.mp3',
    'snd/fart.mp3',
    'snd/knuckles.mp3',
    'snd/rimshot.mp3',
    'snd/scream.mp3',
    'snd/whip.wav',
];

/**
 * What generation of the model cache this build wants, from the pinned digests
 * in `scripts/pose-model.sha256`.
 *
 * The digests rather than the bytes, deliberately: `public/mp/` is fetched by
 * `postinstall` and is not in git, so it may well be absent when a tool reads
 * this file, while the pin is checked in and is the thing `fetch-pose-model.mjs`
 * refuses to ship anything else against. The two are the same answer, and only
 * one of them is always there.
 */
function modelVersion() {
    const text = readFileSync(resolve(here, 'pose-model.sha256'), 'utf8');
    const digests = text.split('\n')
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith('#'))
        .map((l) => l.split(/\s+/)[0])
        .sort()
        .join('\n');
    return createHash('sha256').update(digests).digest('hex').slice(0, 16);
}

const worker = (version, model, files) => `/* Generated by scripts/pwa.mjs - do not edit. */
const SHELL_CACHE = 'deshrimp-shell-${version}';
const MODEL_CACHE = 'deshrimp-model-${model}';
const SHELL = ${JSON.stringify(files, null, 4)};

/* Everything the pose model needs, and the only thing kept across a deploy.
   Resolved against this worker's own URL rather than the origin root, because
   the site is also served from a subdirectory: GitHub Pages puts pull request
   previews under /pr-preview/<pr>/commit-<sha>/. */
const MODEL_DIR = new URL('mp/', self.location.href).href;

const isModel = (url) => url.href.startsWith(MODEL_DIR);

self.addEventListener('install', (event) => {
    // Individually, so one missing file cannot fail the whole install.
    event.waitUntil((async () => {
        const cache = await caches.open(SHELL_CACHE);
        await Promise.all(SHELL.map((f) => cache.add(f).catch(() => {})));
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        // The model cache survives here as long as the pin behind its name
        // does. That is the difference between a deploy and a re-download.
        const keep = new Set([SHELL_CACHE, MODEL_CACHE]);
        const names = await caches.keys();
        await Promise.all(names.filter((n) => !keep.has(n)).map((n) => caches.delete(n)));
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // A navigation gets its own page back when we have it - /de.html is a
    // different page from / in one respect that matters offline, which is the
    // language it opens in - and the root shell otherwise.
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            try {
                return await fetch(request);
            } catch {
                const cache = await caches.open(SHELL_CACHE);
                return (await cache.match(request, { ignoreSearch: true }))
                    || (await cache.match('./index.html'))
                    || Response.error();
            }
        })());
        return;
    }

    // Everything else: serve from cache when it is there, otherwise fetch and
    // keep a copy. This is what pulls the pose model in on first use.
    event.respondWith((async () => {
        const model = isModel(url);
        const cache = await caches.open(model ? MODEL_CACHE : SHELL_CACHE);
        const hit = await cache.match(request);
        if (hit) return hit;
        try {
            /* The model files have no hash in their names, so on a miss the
               HTTP cache could hand back bytes from before the pin moved, and
               they would then be stored under a name that promises otherwise.
               'no-cache' revalidates instead of re-downloading: a matching
               ETag is a 304 and the body still comes from the HTTP cache. */
            const response = await fetch(
                model ? new Request(request, { cache: 'no-cache' }) : request,
            );
            if (response.ok && response.type === 'basic') {
                void cache.put(request, response.clone());
            }
            return response;
        } catch {
            return Response.error();
        }
    })());
});
`;

export default function pwa() {
    return {
        name: 'deshrimp-pwa',
        apply: 'build',
        generateBundle(_options, bundle) {
            const built = Object.values(bundle)
                .map((chunk) => chunk.fileName)
                .filter((name) => name.endsWith('.js') || name.endsWith('.css')
                    || name.endsWith('.woff2'));

            // The bundle hashes change whenever anything does, so hashing the
            // list is enough to name a cache generation.
            const version = [...built, ...PAGES, ...STATIC].join('|').split('').reduce(
                (h, c) => (Math.imul(31, h) + c.charCodeAt(0)) | 0, 7,
            ).toString(36).replace('-', 'z');

            const files = [
                './index.html',
                ...PAGES,
                ...built.map((f) => `./${f}`),
                ...STATIC.map((f) => `./${f}`),
            ];
            this.emitFile({
                type: 'asset',
                fileName: 'sw.js',
                source: worker(version, modelVersion(), files),
            });
        },
    };
}
