/**
 * The service worker, generated at build time.
 *
 * A manifest alone does not make a page installable - Chromium wants a service
 * worker with a fetch handler before it offers the install prompt. And a page
 * whose whole point is that it needs no server should keep working when there
 * is none, so this is a real offline cache rather than a formality.
 *
 * What goes where:
 *
 * - **Precached** on install: the shell (the root HTML *and* the thirteen
 *   per-language pages, which are the same page with another head and another
 *   prerendered block, so they are a few KB each), the JS and CSS, the brand
 *   type, the icon and mark, the manifest and all six sounds. A
 *   posture watcher whose alarm is silent offline is not one, and an interface
 *   that falls back to the system sans offline is one that looks broken on the
 *   day the network is gone.
 * - **Cached on first use**: the pose model under `mp/`. It is ~17 MB, so
 *   forcing it through the install step would mean a page that appears to hang
 *   on first visit. It lands in the cache the first time the camera runs.
 *
 * The precache list is written from the real bundle, so it carries the hashed
 * filenames and a new build invalidates the old cache by name.
 */

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LANGS } from './seo.mjs';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The per-language pages (`de.html`, `ja.html`, ...). `scripts/seo.mjs` writes
 * them after the bundle, so they are not in it either - and a site that is one
 * URL per language must be able to open the URL that was installed, not only
 * the root one, when the network is gone.
 */
const PAGES = LANGS.map((l) => `./${l}.html`);

/** Served as-is out of `public/`, so Vite's bundle does not list them. */
const STATIC = [
    'icon.svg',
    'icon-maskable.svg',
    'manifest.webmanifest',
    'brand/logo.svg',
    'brand/mark.svg',
    'snd/ahem.mp3',
    'snd/fart.mp3',
    'snd/knuckles.mp3',
    'snd/rimshot.mp3',
    'snd/scream.mp3',
    'snd/whip.wav',
];

const worker = (version, files) => `/* Generated by scripts/pwa.mjs - do not edit. */
const CACHE = 'deshrimp-${version}';
const SHELL = ${JSON.stringify(files, null, 4)};

self.addEventListener('install', (event) => {
    // Individually, so one missing file cannot fail the whole install.
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        await Promise.all(SHELL.map((f) => cache.add(f).catch(() => {})));
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const names = await caches.keys();
        await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
        await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // A navigation gets its own page back when we have it - /de.html is a
    // different page from / in one respect that matters offline, which is the
    // language it opens in - and the root shell otherwise.
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            try {
                return await fetch(request);
            } catch {
                return (await caches.match(request, { ignoreSearch: true }))
                    || (await caches.match('./index.html'))
                    || Response.error();
            }
        })());
        return;
    }

    // Everything else: serve from cache when it is there, otherwise fetch and
    // keep a copy. This is what pulls the pose model in on first use.
    event.respondWith((async () => {
        const hit = await caches.match(request);
        if (hit) return hit;
        try {
            const response = await fetch(request);
            if (response.ok && response.type === 'basic') {
                const cache = await caches.open(CACHE);
                void cache.put(request, response.clone());
            }
            return response;
        } catch {
            return Response.error();
        }
    })());
});
`;

export default function pwa() {
    return {
        name: 'deshrimp-pwa',
        apply: 'build',
        generateBundle(_options, bundle) {
            const built = Object.values(bundle)
                .map((chunk) => chunk.fileName)
                .filter((name) => name.endsWith('.js') || name.endsWith('.css')
                    || name.endsWith('.woff2'));

            // The bundle hashes change whenever anything does, so hashing the
            // list is enough to name a cache generation.
            const version = readFileSync(resolve(here, '..', 'package.json'), 'utf8')
                && [...built, ...PAGES, ...STATIC].join('|').split('').reduce(
                    (h, c) => (Math.imul(31, h) + c.charCodeAt(0)) | 0, 7,
                ).toString(36).replace('-', 'z');

            const files = [
                './index.html',
                ...PAGES,
                ...built.map((f) => `./${f}`),
                ...STATIC.map((f) => `./${f}`),
            ];
            this.emitFile({ type: 'asset', fileName: 'sw.js', source: worker(version, files) });
        },
    };
}
